-- MySQL Script generated by MySQL Workbench
-- Sat Aug  5 00:28:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_trabajo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_trabajo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_trabajo` DEFAULT CHARACTER SET utf8 ;
USE `db_trabajo` ;

-- -----------------------------------------------------
-- Table `db_trabajo`.`tbl_postulacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_trabajo`.`tbl_postulacion` (
  `postulacion_id` INT(11) NOT NULL,
  `postulacion_fecha` DATE NOT NULL,
  `postulacion_titulo` TEXT NULL,
  `postulacion_descripcion` TEXT NULL,
  `postulacion_salario` VARCHAR(20) NOT NULL,
  `postulacion_modalidad` TEXT NULL,
  PRIMARY KEY (`postulacion_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_trabajo`.`tbl_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_trabajo`.`tbl_empresa` (
  `empresa_id` INT(11) NOT NULL,
  `empresa_nombre` TEXT NULL,
  `empresa_ubicacion` TEXT NULL,
  `empresa_url` TEXT NULL,
  `tbl_postulacion` INT(11) NOT NULL,
  PRIMARY KEY (`empresa_id`),
  CONSTRAINT `fk_tbl_empresa_tbl_postulacion`
    FOREIGN KEY (`tbl_postulacion`)
    REFERENCES `db_trabajo`.`tbl_postulacion` (`postulacion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
